<?php
/**
 * Sofinco Epayment module for Magento
 *
 * Feel free to contact Sofinco at support@paybox.com for any
 * question.
 *
 * LICENSE: This source file is subject to the version 3.0 of the Open
 * Software License (OSL-3.0) that is available through the world-wide-web
 * at the following URI: http://opensource.org/licenses/OSL-3.0. If
 * you did not receive a copy of the OSL-3.0 license and are unable
 * to obtain it through the web, please send a note to
 * support@paybox.com so we can mail you a copy immediately.
 *
 * @version   1.0.7-psr
 * @author    BM Services <contact@bm-services.com>
 * @copyright 2012-2017 Sofinco
 * @license   http://opensource.org/licenses/OSL-3.0
 * @link      http://www.paybox.com/
 */

namespace Sofinco\Epayment\Model;

class IsoCountry
{
    private $_mapping = [
        'AD' => '20',
        'AE' => '784',
        'AF' => '4',
        'AG' => '28',
        'AI' => '660',
        'AL' => '8',
        'AM' => '51',
        'AO' => '24',
        'AQ' => '10',
        'AR' => '32',
        'AS' => '16',
        'AT' => '40',
        'AU' => '36',
        'AW' => '533',
        'AX' => '248',
        'AZ' => '31',
        'BA' => '70',
        'BB' => '52',
        'BD' => '50',
        'BE' => '56',
        'BF' => '854',
        'BG' => '100',
        'BH' => '48',
        'BI' => '108',
        'BJ' => '204',
        'BL' => '652',
        'BM' => '60',
        'BN' => '96',
        'BO' => '68',
        'BQ' => '535',
        'BR' => '76',
        'BS' => '44',
        'BT' => '64',
        'BV' => '74',
        'BW' => '72',
        'BY' => '112',
        'BZ' => '84',
        'CA' => '124',
        'CC' => '166',
        'CD' => '180',
        'CF' => '140',
        'CG' => '178',
        'CH' => '756',
        'CI' => '384',
        'CK' => '184',
        'CL' => '152',
        'CM' => '120',
        'CN' => '156',
        'CO' => '170',
        'CR' => '188',
        'CU' => '192',
        'CV' => '132',
        'CW' => '531',
        'CX' => '162',
        'CY' => '196',
        'CZ' => '203',
        'DE' => '276',
        'DJ' => '262',
        'DK' => '208',
        'DM' => '212',
        'DO' => '214',
        'DZ' => '12',
        'EC' => '218',
        'EE' => '233',
        'EG' => '818',
        'EH' => '732',
        'ER' => '232',
        'ES' => '724',
        'ET' => '231',
        'FI' => '246',
        'FJ' => '242',
        'FK' => '238',
        'FM' => '583',
        'FO' => '234',
        'FR' => '250',
        'GA' => '266',
        'GB' => '826',
        'GD' => '308',
        'GE' => '268',
        'GF' => '254',
        'GG' => '831',
        'GH' => '288',
        'GI' => '292',
        'GL' => '304',
        'GM' => '270',
        'GN' => '324',
        'GP' => '312',
        'GQ' => '226',
        'GR' => '300',
        'GS' => '239',
        'GT' => '320',
        'GU' => '316',
        'GW' => '624',
        'GY' => '328',
        'HK' => '344',
        'HM' => '334',
        'HN' => '340',
        'HR' => '191',
        'HT' => '332',
        'HU' => '348',
        'ID' => '360',
        'IE' => '372',
        'IL' => '376',
        'IM' => '833',
        'IN' => '356',
        'IO' => '86',
        'IQ' => '368',
        'IR' => '364',
        'IS' => '352',
        'IT' => '380',
        'JE' => '832',
        'JM' => '388',
        'JO' => '400',
        'JP' => '392',
        'KE' => '404',
        'KG' => '417',
        'KH' => '116',
        'KI' => '296',
        'KM' => '174',
        'KN' => '659',
        'KP' => '408',
        'KR' => '410',
        'KW' => '414',
        'KY' => '136',
        'KZ' => '398',
        'LA' => '418',
        'LB' => '422',
        'LC' => '662',
        'LI' => '438',
        'LK' => '144',
        'LR' => '430',
        'LS' => '426',
        'LT' => '440',
        'LU' => '442',
        'LV' => '428',
        'LY' => '434',
        'MA' => '504',
        'MC' => '492',
        'MD' => '498',
        'ME' => '499',
        'MF' => '663',
        'MG' => '450',
        'MH' => '584',
        'MK' => '807',
        'ML' => '466',
        'MM' => '104',
        'MN' => '496',
        'MO' => '446',
        'MP' => '580',
        'MQ' => '474',
        'MR' => '478',
        'MS' => '500',
        'MT' => '470',
        'MU' => '480',
        'MV' => '462',
        'MW' => '454',
        'MX' => '484',
        'MY' => '458',
        'MZ' => '508',
        'NA' => '516',
        'NC' => '540',
        'NE' => '562',
        'NF' => '574',
        'NG' => '566',
        'NI' => '558',
        'NL' => '528',
        'NO' => '578',
        'NP' => '524',
        'NR' => '520',
        'NU' => '570',
        'NZ' => '554',
        'OM' => '512',
        'PA' => '591',
        'PE' => '604',
        'PF' => '258',
        'PG' => '598',
        'PH' => '608',
        'PK' => '586',
        'PL' => '616',
        'PM' => '666',
        'PN' => '612',
        'PR' => '630',
        'PS' => '275',
        'PT' => '620',
        'PW' => '585',
        'PY' => '600',
        'QA' => '634',
        'RE' => '638',
        'RO' => '642',
        'RS' => '688',
        'RU' => '643',
        'RW' => '646',
        'SA' => '682',
        'SB' => '90',
        'SC' => '690',
        'SD' => '729',
        'SE' => '752',
        'SG' => '702',
        'SH' => '654',
        'SI' => '705',
        'SJ' => '744',
        'SK' => '703',
        'SL' => '694',
        'SM' => '674',
        'SN' => '686',
        'SO' => '706',
        'SR' => '740',
        'SS' => '728',
        'ST' => '678',
        'SV' => '222',
        'SX' => '534',
        'SY' => '760',
        'SZ' => '748',
        'TC' => '796',
        'TD' => '148',
        'TF' => '260',
        'TG' => '768',
        'TH' => '764',
        'TJ' => '762',
        'TK' => '772',
        'TL' => '626',
        'TM' => '795',
        'TN' => '788',
        'TO' => '776',
        'TR' => '792',
        'TT' => '780',
        'TV' => '798',
        'TW' => '158',
        'TZ' => '834',
        'UA' => '804',
        'UG' => '800',
        'UM' => '581',
        'US' => '840',
        'UY' => '858',
        'UZ' => '860',
        'VA' => '336',
        'VC' => '670',
        'VE' => '862',
        'VG' => '92',
        'VI' => '850',
        'VN' => '704',
        'VU' => '548',
        'WF' => '876',
        'WS' => '882',
        'YE' => '887',
        'YT' => '175',
        'ZA' => '710',
        'ZM' => '894',
        'ZW' => '716',
    ];
	private $_more = [
		'AD'=>array('name'=>'ANDORRA','code'=>'376'),
		'AE'=>array('name'=>'UNITED ARAB EMIRATES','code'=>'971'),
		'AF'=>array('name'=>'AFGHANISTAN','code'=>'93'),
		'AG'=>array('name'=>'ANTIGUA AND BARBUDA','code'=>'1268'),
		'AI'=>array('name'=>'ANGUILLA','code'=>'1264'),
		'AL'=>array('name'=>'ALBANIA','code'=>'355'),
		'AM'=>array('name'=>'ARMENIA','code'=>'374'),
		'AN'=>array('name'=>'NETHERLANDS ANTILLES','code'=>'599'),
		'AO'=>array('name'=>'ANGOLA','code'=>'244'),
		'AQ'=>array('name'=>'ANTARCTICA','code'=>'672'),
		'AR'=>array('name'=>'ARGENTINA','code'=>'54'),
		'AS'=>array('name'=>'AMERICAN SAMOA','code'=>'1684'),
		'AT'=>array('name'=>'AUSTRIA','code'=>'43'),
		'AU'=>array('name'=>'AUSTRALIA','code'=>'61'),
		'AW'=>array('name'=>'ARUBA','code'=>'297'),
		'AZ'=>array('name'=>'AZERBAIJAN','code'=>'994'),
		'BA'=>array('name'=>'BOSNIA AND HERZEGOVINA','code'=>'387'),
		'BB'=>array('name'=>'BARBADOS','code'=>'1246'),
		'BD'=>array('name'=>'BANGLADESH','code'=>'880'),
		'BE'=>array('name'=>'BELGIUM','code'=>'32'),
		'BF'=>array('name'=>'BURKINA FASO','code'=>'226'),
		'BG'=>array('name'=>'BULGARIA','code'=>'359'),
		'BH'=>array('name'=>'BAHRAIN','code'=>'973'),
		'BI'=>array('name'=>'BURUNDI','code'=>'257'),
		'BJ'=>array('name'=>'BENIN','code'=>'229'),
		'BL'=>array('name'=>'SAINT BARTHELEMY','code'=>'590'),
		'BM'=>array('name'=>'BERMUDA','code'=>'1441'),
		'BN'=>array('name'=>'BRUNEI DARUSSALAM','code'=>'673'),
		'BO'=>array('name'=>'BOLIVIA','code'=>'591'),
		'BR'=>array('name'=>'BRAZIL','code'=>'55'),
		'BS'=>array('name'=>'BAHAMAS','code'=>'1242'),
		'BT'=>array('name'=>'BHUTAN','code'=>'975'),
		'BW'=>array('name'=>'BOTSWANA','code'=>'267'),
		'BY'=>array('name'=>'BELARUS','code'=>'375'),
		'BZ'=>array('name'=>'BELIZE','code'=>'501'),
		'CA'=>array('name'=>'CANADA','code'=>'1'),
		'CC'=>array('name'=>'COCOS (KEELING) ISLANDS','code'=>'61'),
		'CD'=>array('name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code'=>'243'),
		'CF'=>array('name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'236'),
		'CG'=>array('name'=>'CONGO','code'=>'242'),
		'CH'=>array('name'=>'SWITZERLAND','code'=>'41'),
		'CI'=>array('name'=>'COTE D IVOIRE','code'=>'225'),
		'CK'=>array('name'=>'COOK ISLANDS','code'=>'682'),
		'CL'=>array('name'=>'CHILE','code'=>'56'),
		'CM'=>array('name'=>'CAMEROON','code'=>'237'),
		'CN'=>array('name'=>'CHINA','code'=>'86'),
		'CO'=>array('name'=>'COLOMBIA','code'=>'57'),
		'CR'=>array('name'=>'COSTA RICA','code'=>'506'),
		'CU'=>array('name'=>'CUBA','code'=>'53'),
		'CV'=>array('name'=>'CAPE VERDE','code'=>'238'),
		'CX'=>array('name'=>'CHRISTMAS ISLAND','code'=>'61'),
		'CY'=>array('name'=>'CYPRUS','code'=>'357'),
		'CZ'=>array('name'=>'CZECH REPUBLIC','code'=>'420'),
		'DE'=>array('name'=>'GERMANY','code'=>'49'),
		'DJ'=>array('name'=>'DJIBOUTI','code'=>'253'),
		'DK'=>array('name'=>'DENMARK','code'=>'45'),
		'DM'=>array('name'=>'DOMINICA','code'=>'1767'),
		'DO'=>array('name'=>'DOMINICAN REPUBLIC','code'=>'1809'),
		'DZ'=>array('name'=>'ALGERIA','code'=>'213'),
		'EC'=>array('name'=>'ECUADOR','code'=>'593'),
		'EE'=>array('name'=>'ESTONIA','code'=>'372'),
		'EG'=>array('name'=>'EGYPT','code'=>'20'),
		'ER'=>array('name'=>'ERITREA','code'=>'291'),
		'ES'=>array('name'=>'SPAIN','code'=>'34'),
		'ET'=>array('name'=>'ETHIOPIA','code'=>'251'),
		'FI'=>array('name'=>'FINLAND','code'=>'358'),
		'FJ'=>array('name'=>'FIJI','code'=>'679'),
		'FK'=>array('name'=>'FALKLAND ISLANDS (MALVINAS)','code'=>'500'),
		'FM'=>array('name'=>'MICRONESIA, FEDERATED STATES OF','code'=>'691'),
		'FO'=>array('name'=>'FAROE ISLANDS','code'=>'298'),
		'FR'=>array('name'=>'FRANCE','code'=>'33'),
		'GA'=>array('name'=>'GABON','code'=>'241'),
		'GB'=>array('name'=>'UNITED KINGDOM','code'=>'44'),
		'GD'=>array('name'=>'GRENADA','code'=>'1473'),
		'GE'=>array('name'=>'GEORGIA','code'=>'995'),
		'GH'=>array('name'=>'GHANA','code'=>'233'),
		'GI'=>array('name'=>'GIBRALTAR','code'=>'350'),
		'GL'=>array('name'=>'GREENLAND','code'=>'299'),
		'GM'=>array('name'=>'GAMBIA','code'=>'220'),
		'GN'=>array('name'=>'GUINEA','code'=>'224'),
		'GQ'=>array('name'=>'EQUATORIAL GUINEA','code'=>'240'),
		'GR'=>array('name'=>'GREECE','code'=>'30'),
		'GT'=>array('name'=>'GUATEMALA','code'=>'502'),
		'GU'=>array('name'=>'GUAM','code'=>'1671'),
		'GW'=>array('name'=>'GUINEA-BISSAU','code'=>'245'),
		'GY'=>array('name'=>'GUYANA','code'=>'592'),
		'HK'=>array('name'=>'HONG KONG','code'=>'852'),
		'HN'=>array('name'=>'HONDURAS','code'=>'504'),
		'HR'=>array('name'=>'CROATIA','code'=>'385'),
		'HT'=>array('name'=>'HAITI','code'=>'509'),
		'HU'=>array('name'=>'HUNGARY','code'=>'36'),
		'ID'=>array('name'=>'INDONESIA','code'=>'62'),
		'IE'=>array('name'=>'IRELAND','code'=>'353'),
		'IL'=>array('name'=>'ISRAEL','code'=>'972'),
		'IM'=>array('name'=>'ISLE OF MAN','code'=>'44'),
		'IN'=>array('name'=>'INDIA','code'=>'91'),
		'IQ'=>array('name'=>'IRAQ','code'=>'964'),
		'IR'=>array('name'=>'IRAN, ISLAMIC REPUBLIC OF','code'=>'98'),
		'IS'=>array('name'=>'ICELAND','code'=>'354'),
		'IT'=>array('name'=>'ITALY','code'=>'39'),
		'JM'=>array('name'=>'JAMAICA','code'=>'1876'),
		'JO'=>array('name'=>'JORDAN','code'=>'962'),
		'JP'=>array('name'=>'JAPAN','code'=>'81'),
		'KE'=>array('name'=>'KENYA','code'=>'254'),
		'KG'=>array('name'=>'KYRGYZSTAN','code'=>'996'),
		'KH'=>array('name'=>'CAMBODIA','code'=>'855'),
		'KI'=>array('name'=>'KIRIBATI','code'=>'686'),
		'KM'=>array('name'=>'COMOROS','code'=>'269'),
		'KN'=>array('name'=>'SAINT KITTS AND NEVIS','code'=>'1869'),
		'KP'=>array('name'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code'=>'850'),
		'KR'=>array('name'=>'KOREA REPUBLIC OF','code'=>'82'),
		'KW'=>array('name'=>'KUWAIT','code'=>'965'),
		'KY'=>array('name'=>'CAYMAN ISLANDS','code'=>'1345'),
		'KZ'=>array('name'=>'KAZAKSTAN','code'=>'7'),
		'LA'=>array('name'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','code'=>'856'),
		'LB'=>array('name'=>'LEBANON','code'=>'961'),
		'LC'=>array('name'=>'SAINT LUCIA','code'=>'1758'),
		'LI'=>array('name'=>'LIECHTENSTEIN','code'=>'423'),
		'LK'=>array('name'=>'SRI LANKA','code'=>'94'),
		'LR'=>array('name'=>'LIBERIA','code'=>'231'),
		'LS'=>array('name'=>'LESOTHO','code'=>'266'),
		'LT'=>array('name'=>'LITHUANIA','code'=>'370'),
		'LU'=>array('name'=>'LUXEMBOURG','code'=>'352'),
		'LV'=>array('name'=>'LATVIA','code'=>'371'),
		'LY'=>array('name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'218'),
		'MA'=>array('name'=>'MOROCCO','code'=>'212'),
		'MC'=>array('name'=>'MONACO','code'=>'377'),
		'MD'=>array('name'=>'MOLDOVA, REPUBLIC OF','code'=>'373'),
		'ME'=>array('name'=>'MONTENEGRO','code'=>'382'),
		'MF'=>array('name'=>'SAINT MARTIN','code'=>'1599'),
		'MG'=>array('name'=>'MADAGASCAR','code'=>'261'),
		'MH'=>array('name'=>'MARSHALL ISLANDS','code'=>'692'),
		'MK'=>array('name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code'=>'389'),
		'ML'=>array('name'=>'MALI','code'=>'223'),
		'MM'=>array('name'=>'MYANMAR','code'=>'95'),
		'MN'=>array('name'=>'MONGOLIA','code'=>'976'),
		'MO'=>array('name'=>'MACAU','code'=>'853'),
		'MP'=>array('name'=>'NORTHERN MARIANA ISLANDS','code'=>'1670'),
		'MR'=>array('name'=>'MAURITANIA','code'=>'222'),
		'MS'=>array('name'=>'MONTSERRAT','code'=>'1664'),
		'MT'=>array('name'=>'MALTA','code'=>'356'),
		'MU'=>array('name'=>'MAURITIUS','code'=>'230'),
		'MV'=>array('name'=>'MALDIVES','code'=>'960'),
		'MW'=>array('name'=>'MALAWI','code'=>'265'),
		'MX'=>array('name'=>'MEXICO','code'=>'52'),
		'MY'=>array('name'=>'MALAYSIA','code'=>'60'),
		'MZ'=>array('name'=>'MOZAMBIQUE','code'=>'258'),
		'NA'=>array('name'=>'NAMIBIA','code'=>'264'),
		'NC'=>array('name'=>'NEW CALEDONIA','code'=>'687'),
		'NE'=>array('name'=>'NIGER','code'=>'227'),
		'NG'=>array('name'=>'NIGERIA','code'=>'234'),
		'NI'=>array('name'=>'NICARAGUA','code'=>'505'),
		'NL'=>array('name'=>'NETHERLANDS','code'=>'31'),
		'NO'=>array('name'=>'NORWAY','code'=>'47'),
		'NP'=>array('name'=>'NEPAL','code'=>'977'),
		'NR'=>array('name'=>'NAURU','code'=>'674'),
		'NU'=>array('name'=>'NIUE','code'=>'683'),
		'NZ'=>array('name'=>'NEW ZEALAND','code'=>'64'),
		'OM'=>array('name'=>'OMAN','code'=>'968'),
		'PA'=>array('name'=>'PANAMA','code'=>'507'),
		'PE'=>array('name'=>'PERU','code'=>'51'),
		'PF'=>array('name'=>'FRENCH POLYNESIA','code'=>'689'),
		'PG'=>array('name'=>'PAPUA NEW GUINEA','code'=>'675'),
		'PH'=>array('name'=>'PHILIPPINES','code'=>'63'),
		'PK'=>array('name'=>'PAKISTAN','code'=>'92'),
		'PL'=>array('name'=>'POLAND','code'=>'48'),
		'PM'=>array('name'=>'SAINT PIERRE AND MIQUELON','code'=>'508'),
		'PN'=>array('name'=>'PITCAIRN','code'=>'870'),
		'PR'=>array('name'=>'PUERTO RICO','code'=>'1'),
		'PT'=>array('name'=>'PORTUGAL','code'=>'351'),
		'PW'=>array('name'=>'PALAU','code'=>'680'),
		'PY'=>array('name'=>'PARAGUAY','code'=>'595'),
		'QA'=>array('name'=>'QATAR','code'=>'974'),
		'RO'=>array('name'=>'ROMANIA','code'=>'40'),
		'RS'=>array('name'=>'SERBIA','code'=>'381'),
		'RU'=>array('name'=>'RUSSIAN FEDERATION','code'=>'7'),
		'RW'=>array('name'=>'RWANDA','code'=>'250'),
		'SA'=>array('name'=>'SAUDI ARABIA','code'=>'966'),
		'SB'=>array('name'=>'SOLOMON ISLANDS','code'=>'677'),
		'SC'=>array('name'=>'SEYCHELLES','code'=>'248'),
		'SD'=>array('name'=>'SUDAN','code'=>'249'),
		'SE'=>array('name'=>'SWEDEN','code'=>'46'),
		'SG'=>array('name'=>'SINGAPORE','code'=>'65'),
		'SH'=>array('name'=>'SAINT HELENA','code'=>'290'),
		'SI'=>array('name'=>'SLOVENIA','code'=>'386'),
		'SK'=>array('name'=>'SLOVAKIA','code'=>'421'),
		'SL'=>array('name'=>'SIERRA LEONE','code'=>'232'),
		'SM'=>array('name'=>'SAN MARINO','code'=>'378'),
		'SN'=>array('name'=>'SENEGAL','code'=>'221'),
		'SO'=>array('name'=>'SOMALIA','code'=>'252'),
		'SR'=>array('name'=>'SURINAME','code'=>'597'),
		'ST'=>array('name'=>'SAO TOME AND PRINCIPE','code'=>'239'),
		'SV'=>array('name'=>'EL SALVADOR','code'=>'503'),
		'SY'=>array('name'=>'SYRIAN ARAB REPUBLIC','code'=>'963'),
		'SZ'=>array('name'=>'SWAZILAND','code'=>'268'),
		'TC'=>array('name'=>'TURKS AND CAICOS ISLANDS','code'=>'1649'),
		'TD'=>array('name'=>'CHAD','code'=>'235'),
		'TG'=>array('name'=>'TOGO','code'=>'228'),
		'TH'=>array('name'=>'THAILAND','code'=>'66'),
		'TJ'=>array('name'=>'TAJIKISTAN','code'=>'992'),
		'TK'=>array('name'=>'TOKELAU','code'=>'690'),
		'TL'=>array('name'=>'TIMOR-LESTE','code'=>'670'),
		'TM'=>array('name'=>'TURKMENISTAN','code'=>'993'),
		'TN'=>array('name'=>'TUNISIA','code'=>'216'),
		'TO'=>array('name'=>'TONGA','code'=>'676'),
		'TR'=>array('name'=>'TURKEY','code'=>'90'),
		'TT'=>array('name'=>'TRINIDAD AND TOBAGO','code'=>'1868'),
		'TV'=>array('name'=>'TUVALU','code'=>'688'),
		'TW'=>array('name'=>'TAIWAN, PROVINCE OF CHINA','code'=>'886'),
		'TZ'=>array('name'=>'TANZANIA, UNITED REPUBLIC OF','code'=>'255'),
		'UA'=>array('name'=>'UKRAINE','code'=>'380'),
		'UG'=>array('name'=>'UGANDA','code'=>'256'),
		'US'=>array('name'=>'UNITED STATES','code'=>'1'),
		'UY'=>array('name'=>'URUGUAY','code'=>'598'),
		'UZ'=>array('name'=>'UZBEKISTAN','code'=>'998'),
		'VA'=>array('name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'39'),
		'VC'=>array('name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'1784'),
		'VE'=>array('name'=>'VENEZUELA','code'=>'58'),
		'VG'=>array('name'=>'VIRGIN ISLANDS, BRITISH','code'=>'1284'),
		'VI'=>array('name'=>'VIRGIN ISLANDS, U.S.','code'=>'1340'),
		'VN'=>array('name'=>'VIET NAM','code'=>'84'),
		'VU'=>array('name'=>'VANUATU','code'=>'678'),
		'WF'=>array('name'=>'WALLIS AND FUTUNA','code'=>'681'),
		'WS'=>array('name'=>'SAMOA','code'=>'685'),
		'XK'=>array('name'=>'KOSOVO','code'=>'381'),
		'YE'=>array('name'=>'YEMEN','code'=>'967'),
		'YT'=>array('name'=>'MAYOTTE','code'=>'262'),
		'ZA'=>array('name'=>'SOUTH AFRICA','code'=>'27'),
		'ZM'=>array('name'=>'ZAMBIA','code'=>'260'),
		'ZW'=>array('name'=>'ZIMBABWE','code'=>'263'),
	];
    /**
     * Return ISO country code from Magento country code
     *
     * @param  string $code Magento country code
     * @return string ISO country code
     */
    public function getIsoCode($magentoCode, $default = null)
    {
        if (isset($this->_mapping[$magentoCode])) {
            return $this->_mapping[$magentoCode];
        }
        return $default;
    }
	
	public function getPhoneCode($magentoCode){
        if (isset($this->_more[$magentoCode])) {
            return "+".$this->_more[$magentoCode]['code'];
        }
		return null;
	}
	
	public function getName($magentoCode){
        if (isset($this->_more[$magentoCode])) {
            return $this->_more[$magentoCode]['name'];
        }
		return null;
	}
}
