<?php
/**
 * Verifone e-commerce Epayment module for Magento
 *
 * Feel free to contact Verifone e-commerce at support@paybox.com for any
 * question.
 *
 * LICENSE: This source file is subject to the version 3.0 of the Open
 * Software License (OSL-3.0) that is available through the world-wide-web
 * at the following URI: http://opensource.org/licenses/OSL-3.0. If
 * you did not receive a copy of the OSL-3.0 license and are unable
 * to obtain it through the web, please send a note to
 * support@paybox.com so we can mail you a copy immediately.
 *
 * @version   1.0.12-sfco
 * @author    BM Services <contact@bm-services.com>
 * @copyright 2012-2017 Verifone e-commerce
 * @license   http://opensource.org/licenses/OSL-3.0
 * @link      http://www.paybox.com/
 */
?>
<div id="sofinco-pres">
   <img width="20%" height="20%" src="<?php
         echo $this->getViewFileUrl('Sofinco_Epayment::images/Sofinco.png');
   ?>">
</div>
<div id="sofinco-pres">
   <p>Le paiement 3XCB permet à vos clients de régler en 2, 3 ou 4 fois via une souscription simple, rapide et efficace augmentant votre panier moyen et votre taux de conversion. Il s’adresse aux particuliers majeurs ayant une carte bancaire CB Française. </p>
</div>
